# Generated by Django 6.0.4 on 2026-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dteday', models.DateField()),
                ('season', models.IntegerField()),
                ('yr', models.IntegerField()),
                ('mnth', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('holiday', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('workingday', models.IntegerField()),
                ('weathersit', models.IntegerField()),
                ('temp', models.FloatField()),
                ('atemp', models.FloatField()),
                ('hum', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('casual', models.IntegerField()),
                ('registered', models.IntegerField()),
                ('cnt', models.IntegerField()),
                ('daily_total', models.IntegerField()),
                ('weather_name', models.CharField(max_length=50)),
                ('season_name', models.CharField(max_length=50)),
                ('cluster', models.IntegerField()),
                ('pca_1', models.FloatField(blank=True, null=True)),
                ('pca_2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
